### PR TITLE
Enable teleport by default

### PR DESCRIPTION
**Pull request by tuladhar**
Towards https://github.com/giantswarm/roadmap/issues/3036

### Please check if PR meets these requirements

- [ ] Results of the diffs have been examined and no unintended changes are being introduced.

### Helper

* to disable the GH Action generating manifests diffs for installations, between target and source branches, comment the `/no_diffs_printing` on the PR.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Review by fiunchinho — APPROVED** [review]

**Comment by erkanerol** [comment]
I tested this PR with `capi-flatcar-stable-1.24.17-gen2-gs:3510.2.5` and it worked. We will update the default image with a separate PR before creating the new release.

**Review by erkanerol — APPROVED** [review]

**Pull request merged**
