### PR TITLE
Remove kubectlImage and kubernetesVersion from internal

### PR DESCRIPTION
**Pull request by njuettner**
### What this PR does / why we need it

Unused values, can be dropped.

Towards: https://github.com/giantswarm/roadmap/issues/3670

### Checklist

- [x] Updated CHANGELOG.md.

### Trigger E2E tests

/run cluster-test-suites

### CODE REVIEW

**Review by Gacko — APPROVED** [review]

**Review by AverageMarcus — APPROVED** [review]

**Comment by njuettner** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capz/private

**Comment by njuettner** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capz/private

**Comment by njuettner** [comment]
Merging this for now there is an ongoing issue for CAPZ private: https://github.com/giantswarm/giantswarm/issues/31617

**Pull request merged**
