### PR TITLE
teleport.service: Secure SSH access via Teleport

### PR DESCRIPTION
**Pull request by tuladhar**
Towards https://github.com/giantswarm/roadmap/issues/2697

### Please check if PR meets these requirements

- [ ] Results of the diffs have been examined and no unintended changes are being introduced.

### Helper

* to disable the GH Action generating manifests diffs for installations, between target and source branches, comment the `/no_diffs_printing` on the PR.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by kopiczko** [comment]
A few remarks here:

1. Can't we already create a subchart like in cluster-aws?
2. Why donwload scripts are here? Shouldn't that be baked into the image?

**Comment by tuladhar** [comment]
> A few remarks here:
> 
> 1. Can't we already create a subchart like in cluster-aws?
> 2. Why donwload scripts are here? Shouldn't that be baked into the image?

1. Yes, once we test on cluster-aws, will bring those changes here.
2. For testing purpose only, ultimately it will use baked image.

**Review by whites11 — APPROVED** [review]
lgtmiiwfy

**Pull request merged**
