### PR TITLE
Add Eviction settings and Kube-reserved settings to machinepools

### PR DESCRIPTION
**Pull request by primeroz**
Towards https://github.com/giantswarm/roadmap/issues/1837

- Initial Work on a script to determine node reservations
- Add eviction soft and hard settings to MachinePools

### CODE REVIEW

**Comment by primeroz** [comment]
Numbers are up for discussion ( as well as implementation of course )

Do you think those numbers are too aggressive / reserving too much ? Especially on small nodes

**Comment by bavarianbidi** [comment]
> **note** we are not setting the [`enforcing flag`](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#:~:text=To%20optionally%20enforce%20kube%2Dreserved%20on%20kubernetes%20system%20daemons%2C%20specify%20the%20parent%20control%20group%20for%20kube%20daemons%20as%20the%20value%20for%20%2D%2Dkube%2Dreserved%2Dcgroup%20kubelet%20flag.) so kubelet will be able to grow outside of the reservation which are purely from an `allocatable` point of view

is there a reason for not setting `--system-reserved` (xref: [documentation](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#system-reserved))?

If it's configured we protect `sshd`, `kubelet` and e.g. `systemd-timesyncd` (or whatever the time-daemon might be) to be `OOMKilled` by the kernel if some customer pods are going crazy.
As if the resources of the pod-cgroup exceeds `nodeMemory` - `systemReserved` it starts to OOMKill processes in the pod cgroup.

**Comment by bavarianbidi** [comment]
**softEvictionThresholds**:
```diff
- `memory.available<500Mi,nodefs.available<15%,nodefs.inodesFree<5%,imagefs.available<15%`
+ `memory.available<500Mi,nodefs.available<15%,nodefs.inodesFree<5%,imagefs.available<15%,pid.available<30%`
```

**hardEvictionThresholds**:
```diff
- `memory.available<200Mi,nodefs.available<10%,nodefs.inodesFree<3%,imagefs.available<10%`
+ `memory.available<200Mi,nodefs.available<10%,nodefs.inodesFree<3%,imagefs.available<10%,pid.available<20%`
```

**softEvictionGracePeriod**
```diff
- `memory.available=2m,nodefs.available=2m,nodefs.inodesFree=2m,imagefs.available=2m`
+ `memory.available=30s,nodefs.available=2m,nodefs.inodesFree=1m,imagefs.available=2m,pid.available=1m`
```

i would also recommend to set the `--eviction-minimum-reclaim` flag (xref: [documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#minimum-eviction-reclaim))
**evictionMinimumReclaim**
```diff
+ `imagefs.available=5%,memory.available=100Mi,nodefs.available=5%`
```

**Comment by primeroz** [comment]
> is there a reason for not setting --system-reserved (xref: [documentation](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#system-reserved))?

Unless we also `enforce it` then setting the reserved will just be used to calculate the allocatable amount on each node, this is true for the `kubelet-reserved` as well

I would be very _wary_ of setting the `enforcement` for either of them without extensive profiling because it will prevent those processes to grow over the amount of resources allocated , possibly causing more problems ( xref: [Guidelines on enforcement](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#enforcing-node-allocatable:~:text=Be%20extra%20careful,is%20oom%2Dkilled.) )

we could set the `system-reserved` to just cut some more out of the allocatable of the node but it would not be different from reserving it for kubelet in terms of actual effect on the node. 

I _did_ feel i was already reserving too much :)

**Review by bavarianbidi — APPROVED** [review]

**Pull request merged**
