### PR TITLE
Bump flatcar to latest version

### PR DESCRIPTION
**Pull request by mnitchev**
### Please check if PR meets these requirements

- [x] Results of the diffs have been examined and no unintended changes are being introduced.

### Helper

* to disable the GH Action generating manifests diffs for installations, between target and source branches, comment the `/no_diffs_printing` on the PR.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by calvix** [comment]
probabbly a stupid question but did you have to build the flatcar with the latest version manually or was it already built by CI?

**Comment by mnitchev** [comment]
Since main is broken I tested it here https://github.com/giantswarm/cluster-azure/pull/258. I also ssh-ed into the nodes to check the version

**Comment by mnitchev** [comment]
> probabbly a stupid question but did you have to build the flatcar with the latest version manually or was it already built by CI?

I had to build it manually. It's how it's done for all providers at the moment

**Review by AndiDog — APPROVED** [review]
LGTM once tests are passing

**Pull request merged**
