### PR TITLE
preventDeletion addition

### PR DESCRIPTION
**Pull request by ssyno**
Towards: https://github.com/giantswarm/kubectl-gs/commit/995b6e0b60c98608930ca4deb3f45230af61cec9
This PR:
- adds support on `cluster-azure` chart for `preventDeletion` flag.

### Please check if PR meets these requirements

- [x] Results of the diffs have been examined and no unintended changes are being introduced.

### Helper

* to disable the GH Action generating manifests diffs for installations, between target and source branches, comment the `/no_diffs_printing` on the PR.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Review by fiunchinho — CHANGES_REQUESTED** [review]
Please mention this change in the CHANGELOG. Otherwise LGTM!

**Review by fiunchinho — APPROVED** [review]

**Comment by ssyno** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capz/standard

**Comment by ssyno** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capz/standard

**Pull request merged**
