### PR TITLE
Skip kube-proxy phase to be replaced with cilium

### PR DESCRIPTION
**Pull request by primeroz**
Towards https://github.com/giantswarm/giantswarm/issues/25360 

### Please check if PR meets these requirements

- [x] Results of the diffs have been examined and no unintended changes are being introduced.

### Helper

* to disable the GH Action generating manifests diffs for installations, between target and source branches, comment the `/no_diffs_printing` on the PR.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by primeroz** [comment]
Interestingly the e2e passed for this https://tekton.ei9o7.k8s.gorilla.eu-central-1.aws.gigantic.io/#/namespaces/tekton-pipelines/pipelineruns/pr-cluster-azure-106-cluster-test-suitesjglkl?pipelineTask=run-tests&step=run-tests 

```
  {"level":"info","ts":"2023-04-03T15:54:53Z","msg":"Checking for ready control plane nodes"}
  {"level":"info","ts":"2023-04-03T15:54:53Z","msg":"1 nodes ready, expecting 1"}
```

but it should not have since the `default-apps` installed did not include the cilium kube-proxy replacement values

I will have a look at it and see how come the CP node became ready even though cilium did not start the `kube-proxy` replacement feature 

Maybe it is ok actually , since the CNI was indeed started, and this will be caught by other tests will add later on 

@AverageMarcus FYI ^

**Review by bavarianbidi — APPROVED** [review]
LGTM if network communication still works

**Comment by AverageMarcus** [comment]
> Maybe it is ok actually , since the CNI was indeed started, and this will be caught by other tests will add later on

I suspect that's the case. 

All the current test is doing is waiting until at least 1 control plane node reports being "ready" in the status. The other pods in the cluster could be a complete mess right now and the tests wouldn't care.

**Comment by primeroz** [comment]
connectivity tests https://github.com/giantswarm/giantswarm/issues/25360#issuecomment-1494624179

**Pull request merged**
